export const stylesMotorcycle = [
  "Prototype / concept model",
  "Sport",
  "Scooter",
  "ATV",
  "Allround",
  "Naked bike",
  "Custom / cruiser",
  "Cross / motocross",
  "Super motard",
  "Minibike, sport",
  "Minibike, cross",
  "Classic",
  "Touring",
  "Enduro / offroad",
  "Trial",
  "Unspecified category",
  "Sport touring",
  "Speedway",
] as const;
